// src/app/movies/components/Abilities(old)/AbilitiesWrap.tsx
import { IAbility } from '../Types/Types';

/* interface IProps {
  skills: IAbility[];
  itemName: string;
  handleOnChange(event: React.FormEvent<HTMLInputElement>): void;
  itemText?: string;
} */

/* export const AbilitiesWrap: React.FC<IProps> = ({
  skills,
  itemName,
  handleOnChange,
  itemText,
}: IProps) => {
  return (

  );
};
 */

{
    /* <div className="abilities__item">
      <div className="abilities__text-item">
        <label
          className={`abilities__label ${
            skills.find((item) => item.name === itemName)?.checked
              ? "abilities__label_active"
              : ""
          }`}
          htmlFor={itemName}
        >
          <input
            className="abilities__input"
            id={itemName}
            type="checkbox"
            checked={skills.find((item) => item.name === itemName)?.checked}
            onChange={handleOnChange}
          />
        </label>
        <p className="abilities__subtitle">
          {itemText ? itemText : "Спасбросок"}
        </p>
      </div>
      <div className="abilities__number-item">
        <p className="abilities__subnumber">
          {skills.find((item) => item.name === itemName)?.value}
        </p>
      </div>
    </div> */
}

// src/app/movies/components/abilities/abilities-wrap/abilities-wrap.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { IAbility } from '../../Types/Types';

/**
 *
 * чекбокс для выбора навыка
 */

@Component({
    selector: 'app-abilities-wrap',
    templateUrl: './abilities-wrap.component.html',
    styleUrls: ['./abilities-wrap.component.scss'],
})
export class AbilitiesWrapComponent implements OnInit {
    // handleOnChange(event: React.FormEvent<HTMLInputElement>): void;
    @Input() skills: IAbility[];
    @Input() itemName: string;
    @Output() handleOnChange = new EventEmitter<number>();
    @Input() itemText?: string;
    public value: number = 0;
    public isChecked: boolean = false;

    constructor() {}

    ngOnInit() {
        this.isChecked = !!this.skills.find((item) => item.name === this.itemName)?.checked;
        // this.value = +this.skills.find((item) => item.name === this.itemName)?.value || 0;
    }

    onChange(event: KeyboardEvent) {
        console.log(event);
        // const { id, checked } = event;
    }
}

<div class="abilities__item">
    <div class="abilities__text-item">
        <label [ngClass]="{ abilities__label_active: isChecked }" class="{abilities__label}" htmlFor="{{ itemName }}">
            <input
                class="abilities__input"
                id="{{ itemName }}"
                type="checkbox"
                checked="{{ isChecked }}"
                (keyup)="onChange($event)"
            />
        </label>
        <p class="abilities__subtitle">{{ itemText ? itemText : 'Спасбросок' }}</p>
    </div>
    <div class="abilities__number-item">
        <p class="abilities__subnumber">{{ value }}</p>
    </div>
</div>
